import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./hooks/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#fefcff",
        "surface-container-high": "#e6e8e9",
        surface: "#f8fafb",
        "on-tertiary-container": "#4d3e00",
        "on-surface": "#191c1d",
        "surface-container-highest": "#e1e3e4",
        "surface-container-low": "#f2f4f5",
        "surface-variant": "#e1e3e4",
        "on-surface-variant": "#424751",
        "on-primary": "#ffffff",
        "on-secondary-container": "#007244",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#004689",
        "surface-dim": "#d8dadb",
        "surface-container": "#eceeef",
        "primary-fixed": "#d5e3ff",
        secondary: "#006d40",
        "inverse-surface": "#2e3132",
        "tertiary-container": "#cca800",
        "on-secondary": "#ffffff",
        "surface-bright": "#f8fafb",
        tertiary: "#715c00",
        "inverse-primary": "#a8c8ff",
        "surface-container-lowest": "#ffffff",
        primary: "#165ca9",
        "on-tertiary-fixed": "#231b00",
        "on-secondary-fixed": "#002110",
        "surface-tint": "#1b5eac",
        "tertiary-fixed-dim": "#ecc300",
        "tertiary-fixed": "#ffe17b",
        "on-tertiary-fixed-variant": "#554500",
        "on-secondary-fixed-variant": "#00522f",
        "on-primary-fixed": "#001b3c",
        "secondary-fixed-dim": "#61dd98",
        "secondary-fixed": "#7efab3",
        "primary-container": "#3a75c4",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f2",
        "error-container": "#ffdad6",
        "secondary-container": "#7bf7b0",
        "on-background": "#191c1d",
        "primary-fixed-dim": "#a8c8ff",
        "outline-variant": "#c2c6d3",
        outline: "#727782",
        background: "#f8fafb",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      boxShadow: {
        ambient: "0 8px 32px rgba(25, 28, 29, 0.06)",
        subtle: "0 4px 24px -4px rgba(25, 28, 29, 0.06), 0 2px 8px -2px rgba(25, 28, 29, 0.04)",
        elevated: "0 12px 32px -4px rgba(25, 28, 29, 0.08), 0 4px 16px -4px rgba(25, 28, 29, 0.06)",
      },
    },
  },
  plugins: [],
};

export default config;
